import networkx as nx
import matplotlib.pyplot as plt

G = nx.DiGraph()
G.add_node('a')
G.add_node('b')
G.add_node('c')
G.add_node('d')
G.add_node('e')
G.add_node('f')
G.add_node('g')
G.add_node('h')
print(G.nodes)
G.add_edge('a','b')
G.add_edge('a','c')
G.add_edge('a','d')
G.add_edge('a','f')
G.add_edge('b','c')
G.add_edge('b','e')
G.add_edge('d','e')
G.add_edge('c','d')
G.add_edge('e','f')
G.add_edge('f','c')
G.add_edge('f','g')
G.add_edge('f','h')
G.add_edge('g','f')
G.add_edge('g','h')
G.add_edge('h','f')
G.add_edge('h','g')
print(G.edges)

nx.draw(G,with_labels=True)
plt.show()
